### ISSUE TITLE
Location to distance calculation

### ISSUE THREAD

**Issue by liammclennan** [ambiata/interview#5]
I am confused about the calculation of distance from locations. Are we meant to assume an infinite 2 dimensional world?

**Comment by markhibberd** [comment]
That is a valid assumption. It isn't really a realistic set of dimensions, it is more just something for the calculation. This or anything like it, it is safe to just make the assumption and document it with the solution.

**Comment by liammclennan** [comment]
Thanks Mark. The wording "traversing the globe" is what made me question the 2d assumption.
